steps:
  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.28.2'
    args: ['-f', './code-micro-videos/docker-compose.yaml', 'up', '-d']

  - id: "Rodando composer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

  - id: "Compiando .env"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

  - id: "Compiando .env.testing"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'cp', '.env.example.testing', '.env.testing']

  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Rodando migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

  - id: "Rodando phpunit"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
