steps:
  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.28.2'
    args: ['-f', './code-micro-videos/docker-compose.prod.yaml', 'up', '-d']

  -   id: "Chown in /var/www"
      name: 'gcr.io/cloud-builders/docker'
      args: ['exec','-u','root','-t','micro-videos-app','chown','-R','www-data:www-data','/var/www']

  - id: "Rodando composer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'composer', 'install']

  - id: "Compiando .env"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'micro-videos-app', 'cp', '.env.example', '.env']

  - id: "Compiando .env.testing"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'cp', '.env.testing.example', '.env.testing']

  - id: "Rodando key:generate"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Rodando Migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/artisan', 'migrate']

  - id: "Rodando Phpunit"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'exec', '-t', 'micro-videos-app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
