
create-model-category:
	php artisan make:model Models/Category --all;

create-model-genre:
	php artisan make:model Models/Genre --all;

run-route-list:
	php artisan route:list;

run-tinker:
	 php artisan tinker;

run-migrate-seed:
	php artisan migrate:refresh --seed;

run-unit-tests:
	 vendor/bin/phpunit;

create-category-test:
	php artisan make:test CategoryTest --unit;

create-category-test-feat:
	php artisan make:test Models/CategoryTest;
